pkg_name: nengo_dl
repo_name: nengo/nengo-dl

script_config:
  static:
    pip_install:
      - -e .[all]
    conda_install:
      - pandoc
  test:
    pip_install:
      - -e .[tests]
      - $NUMPY_VERSION
      - $TF_VERSION
      - $NENGO_VERSION
    nengo_tests: true
  examples:
    pip_install:
      - -e .[all]
    custom_commands:
      - python docs/whitepaper/whitepaper2018_code.py > /dev/null
  docs:
    pip_install:
      - -e .[docs]
    conda_install:
      - pandoc

travis_config:
  python_version: 3.6
  global_vars:
    NUMPY_VERSION: numpy
    TF_VERSION: tensorflow
    NENGO_VERSION: nengo
  jobs:
    - script: static
    - script: docs
    - cache: false
    - coverage: true
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git
        TF_VERSION: tensorflow<2.0 --pre
    - coverage: true
      env:
        NENGO_VERSION: nengo==2.7.0
        TF_VERSION: tensorflow==1.4.0
        PIP_UPGRADE_STRATEGY: only-if-needed
    - test_args: --dtype float64 --simulator-only
    - test_args: --unroll-simulation 5 --simulator-only
    - test_args: --inference-only --simulator-only
    - script: examples
      language: generic
  pypi_user: drasmuss
  deploy_dists:
    - sdist

codecov_config: {}
